# Generated by Django 3.0.7 on 2020-07-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='other_days_type',
            field=models.CharField(choices=[('d', 'days'), ('m', 'months'), ('y', 'years')], default='m', max_length=100),
        ),
    ]
