# Generated by Django 3.0.7 on 2020-07-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sleepValue',
            field=models.IntegerField(blank=True, default='none', max_length=100, null=True),
        ),
    ]
