# Generated by Django 3.0.7 on 2020-07-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200712_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sleepValue',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
