# Generated by Django 3.0.7 on 2020-07-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_patient_other_days_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='reportFirst',
            field=models.FileField(blank=True, default='none', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='reportSecond',
            field=models.FileField(blank=True, default='none', null=True, upload_to=''),
        ),
    ]
