# Generated by Django 2.2.2 on 2020-07-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200722_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='currentlyNotUnderAnyMedicationDuration',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='currentlyNotUnderAnyMedicationDurationType',
        ),
    ]
