# Generated by Django 3.0.7 on 2020-07-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200717_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(blank=True, default='2020-06-02', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='hip',
            field=models.IntegerField(blank=True, default='30', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='waist',
            field=models.IntegerField(blank=True, default='28', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(blank=True, default='50', null=True),
        ),
    ]
