# Generated by Django 2.2.2 on 2020-07-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200724_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(blank=True, default='0001-01-01', null=True),
        ),
    ]
