# Generated by Django 2.2.2 on 2020-07-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200724_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='medicalAllergies',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
