# Generated by Django 3.0.7 on 2020-07-17 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200717_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='year8',
        ),
    ]
