# Generated by Django 3.0.7 on 2020-07-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_patient_year8'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='lastPeriodTimeYear',
            new_name='year8',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='lastPeriodTimeMonth',
        ),
    ]
