# Generated by Django 3.0.7 on 2020-07-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200717_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='symptoms10',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
    ]
