# Generated by Django 2.2.2 on 2020-07-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_patient_symptoms10'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='reportFirst',
            field=models.FileField(blank=True, default='none', null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='reportSecond',
            field=models.FileField(blank=True, default='none', null=True, upload_to='files/'),
        ),
    ]
